[general]
import = [
  # "~/.config/alacritty/dank-theme.toml"
  "~/.config/alacritty/my-theme.toml"
]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[terminal.shell]
program = "/usr/bin/fish"
args = ["-c", "~/bin/tests/start_zelliji.sh"]

[window]
decorations = "None"
padding = { x = 12, y = 12 }
opacity = 0.8

[scrolling]
history = 50000

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500
unfocused_hollow = true

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = false

[bell]
duration = 0

[keyboard]
bindings = [
  { key = "C",       mods = "Control|Shift", action = "Copy"  },
  { key = "V",       mods = "Control|Shift", action = "Paste" },
  { key = "N",       mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "Equals",  mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "Minus",   mods = "Control",       action = "DecreaseFontSize" },
  { key = "Key0",    mods = "Control",       action = "ResetFontSize"    },
  { key = "Enter",   mods = "Shift",         chars = "\n" },
]

[font]
size = 16

[font.bold]
family = "FantasqueSansM Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "FantasqueSansM Nerd Font Propo"
style = "Bold Italic"

[font.italic]
family = "FantasqueSansM Nerd Font Propo"
style = "Italic"

[font.normal]
family = "FantasqueSansM Nerd Font Propo"
style = "Regular"
