server_endpoint = "/run/user/1000/clipcat/grpc.sock"
finder = "rofi"
preview_length = 80

[rofi]
line_length = 100
menu_length = 10
menu_prompt = "Clipcat"
extra_arguments = ["-config", "/home/end/.config/rofi/launchers/type-2/style-1.rasi"]

[dmenu]
line_length = 100
menu_length = 30
menu_prompt = "Clipcat"
extra_arguments = []

[choose]
line_length = 100
menu_length = 30
menu_prompt = "Clipcat"
extra_arguments = []

[custom_finder]
program = "fzf"
args = []

[log]
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "INFO"
